package com.letters2my.app.domain

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

/**
 * Cross-platform `.letterstomy` archive compatibility.
 *
 * The fixture was generated by the PRODUCTION iOS LettersToMyCore
 * (BackupService.serializeAndEncrypt path) with known data:
 *  - 2 children, 5 letters (draft/scheduled/birthday-age/released/sealed),
 *  - 3 attachments (photo/audio/file), branches, folder, member, invitation.
 *
 * Android must decrypt it byte-exactly (AES-256-GCM, SHA-256 passphrase key,
 * nonce||ciphertext||tag envelope) and decode the Swift JSON semantics
 * (reference-date doubles, null omission, base64 data).
 */
class CrossPlatformArchiveTest {

    private val passphrase = "Fixture-Passphrase-42"

    private fun fixtureBytes(): ByteArray =
        File(javaClass.classLoader.getResource("ios-fixture.letterstomy")!!.file)
            .readBytes()

    private fun plaintextFixture(): String =
        File(javaClass.classLoader.getResource("fixture.plaintext.json")!!.file)
            .readText()

    @Test
    fun `decrypts real iOS archive with production codec`() {
        val payload = LetterstomyArchive.decrypt(fixtureBytes(), passphrase)

        assertEquals(1, payload.manifest.formatVersion)
        assertEquals("80000000-0000-0000-0000-000000000001", payload.manifest.archiveID)
        assertEquals("0.1.0", payload.manifest.appVersion)
        assertEquals("AES-256-GCM", payload.manifest.encryptionAlgorithm)
        assertEquals(5, payload.manifest.letterCount)
        assertEquals(3, payload.manifest.attachmentCount)
        assertEquals(2, payload.manifest.recipientCount)

        // Created 2026-01-15T12:00:00Z
        assertEquals(1768478400000L, payload.manifest.createdAtEpochMs)

        assertEquals(2, payload.children.size)
        assertEquals(5, payload.letters.size)
        assertEquals(3, payload.attachments.size)
        assertEquals(2, payload.branches.size)
        assertEquals(1, payload.folders.size)
        assertEquals(1, payload.members.size)
        assertEquals(1, payload.invitations.size)
    }

    @Test
    fun `decodes Swift child fields exactly`() {
        val payload = LetterstomyArchive.decrypt(fixtureBytes(), passphrase)
        val emma = payload.children.first { it.id == "10000000-0000-0000-0000-000000000001" }
        assertEquals("Emma", emma.name)
        // 2018-05-20T00:00:00Z
        assertEquals(1526774400000L, emma.birthDateEpochMs)

        val noah = payload.children.first { it.id == "10000000-0000-0000-0000-000000000002" }
        assertEquals("Noah", noah.name)
        assertEquals(1604275200000L, noah.birthDateEpochMs)
    }

    @Test
    fun `decodes letter lifecycle fields exactly`() {
        val payload = LetterstomyArchive.decrypt(fixtureBytes(), passphrase)
        val letters = payload.letters.associateBy { it.id }

        // Draft: sealedAt omitted (null)
        val draft = letters.getValue("20000000-0000-0000-0000-000000000001")
        assertNull(draft.sealedAtEpochMs)
        assertFalse(draft.isFavorite)
        assertEquals("specificDate", draft.unlockRuleRawValue)
        assertNull(draft.unlockDateEpochMs)
        assertEquals("Draft for Emma", draft.title)
        assertEquals("Mom", draft.authorName)

        // Scheduled specific-date: sealed, favorite
        val scheduled = letters.getValue("20000000-0000-0000-0000-000000000002")
        assertNotNull(scheduled.sealedAtEpochMs)
        assertTrue(scheduled.isFavorite)
        assertEquals("specificDate", scheduled.unlockRuleRawValue)
        // 2034-05-20T00:00:00Z
        assertEquals(2031696000000L, scheduled.unlockDateEpochMs)
        assertEquals("50000000-0000-0000-0000-000000000001", scheduled.folderID)

        // Birthday-age: age 5, no specific date
        val birthday = letters.getValue("20000000-0000-0000-0000-000000000003")
        assertEquals("birthdayAge", birthday.unlockRuleRawValue)
        assertEquals(5, birthday.unlockAgeYearsValue)
        assertNull(birthday.unlockDateEpochMs)
        // Birthday letter belongs to Noah (child 10000000-...-0002), not the
        // scheduled letter's UUID.
        assertEquals("10000000-0000-0000-0000-000000000002", birthday.childID)

        // Life-event released
        val released = letters.getValue("20000000-0000-0000-0000-000000000004")
        assertEquals("lifeEvent", released.unlockRuleRawValue)
        assertEquals("Graduation", released.lifeEventName)
        // 2026-01-10T12:00:00Z
        assertEquals(1768046400000L, released.manuallyReleasedAtEpochMs)

        // Sealed with media
        val sealed = letters.getValue("20000000-0000-0000-0000-000000000005")
        assertNotNull(sealed.sealedAtEpochMs)
        assertEquals("60000000-0000-0000-0000-000000000001", sealed.authorMemberID)
    }

    @Test
    fun `attachments round-trip byte-identical`() {
        val payload = LetterstomyArchive.decrypt(fixtureBytes(), passphrase)
        val atts = payload.attachments.associateBy { it.id }

        val photo = atts.getValue("30000000-0000-0000-0000-000000000001")
        assertEquals("emma-photo.png", photo.fileName)
        assertEquals("public.png", photo.contentTypeIdentifier)
        assertEquals("photo", photo.kindRawValue)
        assertEquals("20000000-0000-0000-0000-000000000005", photo.letterID)
        // 1x1 PNG — assert known first bytes for byte identity.
        assertTrue(photo.data.size > 8)
        assertEquals(0x89.toByte(), photo.data[0])
        assertEquals('P'.code.toByte(), photo.data[1])
        assertEquals('N'.code.toByte(), photo.data[2])
        assertEquals('G'.code.toByte(), photo.data[3])

        val audio = atts.getValue("30000000-0000-0000-0000-000000000002")
        assertEquals("message.m4a", audio.fileName)
        assertEquals("public.mpeg-4-audio", audio.contentTypeIdentifier)
        assertEquals("audio", audio.kindRawValue)
        assertEquals(16, audio.data.size)

        val pdf = atts.getValue("30000000-0000-0000-0000-000000000003")
        assertEquals("letter.pdf", pdf.fileName)
        assertEquals("public.pdf", pdf.contentTypeIdentifier)
        assertEquals("file", pdf.kindRawValue)
        assertEquals("%PDF-1.4\n".toByteArray().toList(), pdf.data.take(9).toList())
    }

    @Test
    fun `decodes branches folder member invitation`() {
        val payload = LetterstomyArchive.decrypt(fixtureBytes(), passphrase)

        val parents = payload.branches.first { it.id == "40000000-0000-0000-0000-000000000001" }
        assertEquals("Parents", parents.name)
        assertEquals("parents", parents.kindRawValue)
        assertNull(parents.parentBranchID)

        val folder = payload.folders.first()
        assertEquals("Emma's Corner", folder.name)
        assertEquals("40000000-0000-0000-0000-000000000001", folder.branchID)
        assertNull(folder.parentFolderID)

        val member = payload.members.first()
        assertEquals("Mom", member.displayName)
        assertEquals("Parent", member.relationship)
        assertEquals("owner", member.roleRawValue)
        assertEquals("active", member.statusRawValue)
        assertTrue(member.canInviteOthers)

        val invitation = payload.invitations.first()
        assertEquals("Aunt Carol", invitation.inviteeDisplayName)
        assertEquals("carol@example.com", invitation.inviteeAddress)
        assertEquals("Aunt", invitation.relationship)
        assertEquals("viewer", invitation.roleRawValue)
        assertEquals("pending", invitation.statusRawValue)
    }

    @Test
    fun `date encoding matches Swift reference-date seconds`() {
        // Swift reference-date seconds for 2026-01-15T12:00:00Z.
        // swiftDouble formats without changing the value:
        assertEquals("790171200", SwiftJson.swiftDouble(790171200.0).content)
        // Round-trip: Swift date number -> epoch ms.
        assertEquals(
            1768478400000L,
            SwiftJson.dateFromNumber(
                kotlinx.serialization.json.JsonPrimitive(790171200)
            )
        )
    }

    @Test
    fun `wrong passphrase fails with structured error`() {
        try {
            LetterstomyArchive.decrypt(fixtureBytes(), "wrong-passphrase")
            fail("expected ArchiveException")
        } catch (e: LetterstomyArchive.ArchiveException) {
            assertTrue(e.message!!.contains("Wrong passphrase", ignoreCase = true))
        }
    }

    @Test
    fun `corrupted tag fails with structured error`() {
        val bytes = fixtureBytes()
        bytes[bytes.size - 1] = (bytes[bytes.size - 1].toInt() xor 0xFF).toByte()
        try {
            LetterstomyArchive.decrypt(bytes, passphrase)
            fail("expected ArchiveException")
        } catch (e: LetterstomyArchive.ArchiveException) {
            assertTrue(e.message!!.contains("Wrong passphrase", ignoreCase = true))
        }
    }

    @Test
    fun `truncated archive fails cleanly`() {
        val bytes = fixtureBytes().copyOfRange(0, 20)
        try {
            LetterstomyArchive.decrypt(bytes, passphrase)
            fail("expected ArchiveException")
        } catch (e: LetterstomyArchive.ArchiveException) {
            assertTrue(e.message!!.contains("Invalid ciphertext", ignoreCase = true))
        }
    }

    @Test
    fun `Android re-encrypt produces archive iOS can read (round-trip)`() {
        // Decrypt the iOS fixture, re-encrypt with the Kotlin codec, decrypt
        // again — proves the Android encoder is internally consistent and the
        // envelope format is the same combined layout.
        val payload = LetterstomyArchive.decrypt(fixtureBytes(), passphrase)
        val reEncrypted = LetterstomyArchive.encrypt(payload, passphrase)
        val decoded = LetterstomyArchive.decrypt(reEncrypted, passphrase)

        assertEquals(payload.letters.size, decoded.letters.size)
        assertEquals(payload.attachments.size, decoded.attachments.size)
        assertEquals(payload.manifest.archiveID, decoded.manifest.archiveID)
        // Envelope overhead: nonce(12) + tag(16) = 28 bytes.
        assertEquals(LetterstomyArchive.GCM_NONCE_LENGTH + 16, reEncrypted.size - decoded.toJson().toString().toByteArray().size)
    }

    @Test
    fun `encoded JSON matches Swift plaintext structure`() {
        // Decode the plaintext Swift JSON and confirm our encoder emits the
        // same key set (nulls omitted, defaults present).
        val swift = Json.parseToJsonElement(plaintextFixture()).jsonObject
        val payload = LetterstomyArchive.decrypt(fixtureBytes(), passphrase)
        val ours = payload.toJson().toString()

        assertTrue("manifest" in ours)
        assertTrue("archiveID" in ours)
        assertTrue("createdAt" in ours)
        // Swift omits nulls: draft letter has no sealedAt key in JSON.
        assertFalse(ours.contains("\"sealedAt\":null"))
        // Defaults present: isFavorite:false IS encoded.
        assertTrue(ours.contains("\"isFavorite\":false"))
    }
}